### ISSUE TITLE
[Linux] Startup Pure Issue: `The hostname could not be parsed`

### ISSUE THREAD

**Issue by chaojian-zhang** [Pure-the-Language/Pure#12]
While building and trying to execute `Pure` on Linux, we encounter the following error (while testing on Github codespace):

```
Unhandled exception. System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at System.UriBuilder..ctor(String uri)
   at Core.Services.AssemblyHelper.get_AssemblyDirectory() in /workspaces/Pure/Core/Services/AssemblyHelper.cs:line 12
   at Core.RoslynContext.<.ctor>g__AddDefaultLibraryFolderToEnvironmentPath|17_0() in /workspaces/Pure/Core/Implementation/RoslynContext.cs:line 254
   at Core.RoslynContext..ctor(Boolean importAdditional, Action`1 outputHandler) in /workspaces/Pure/Core/Implementation/RoslynContext.cs:line 245
   at Core.Interpreter.Start(Action`1 outputHandler) in /workspaces/Pure/Core/Interpreter.cs:line 59
   at Pure.Program.Main(String[] args) in /workspaces/Pure/Frontends/Pure/Program.cs:line 17
Aborted (core dumped)
```

In general, building on Linux is fine. This looks like there is an issue with `AddDefaultLibraryFolderToEnvironmentPath()`.

**Comment by chaojian-zhang** [comment]
Per latest [.Net 8 publish](https://github.com/Pure-the-Language/Pure/pull/33):
![image](https://github.com/Pure-the-Language/Pure/assets/7077098/e05642e4-4a37-4bf6-b030-295ea7b8fe81)

(Can quickly setup and test using [.Net](https://github.com/github/dotnet-codespaces) Github Codespace)

**Comment by chaojian-zhang** [comment]
Fixed: https://github.com/Pure-the-Language/Pure/commit/138526908483aeb1f27c1c1d6ca6789d49cacea9

**Comment by chaojian-zhang** [comment]
Fixed: https://github.com/Pure-the-Language/Pure/commit/138526908483aeb1f27c1c1d6ca6789d49cacea9
